services:
  db:
    image: postgres:17.0
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data
    networks:
      - backend-network
    restart: always

  adminer:
    image: adminer:4.8.1
    ports:
      - "8888:8080"
    networks:
      - backend-network
    depends_on:
      - db
    restart: always

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.5
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "9090:8080"
    volumes:
      - ./event-ticket-platform-realm.json:/opt/keycloak/data/import/event-ticket-platform-realm.json:z
    command:
      - start-dev
      - --db=dev-file
      - --import-realm
    networks:
      - backend-network
    restart: always

networks:
  backend-network:
    driver: bridge
