services:
  db:
    image: postgres:17.0
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data
    networks:
      - backend-network
    restart: always

  adminer:
    image: adminer:4.8.1
    ports:
      - "8888:8080"
    networks:
      - backend-network
    depends_on:
      - db
    restart: always

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.5
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "9090:8080"
    volumes:
      - ./event-ticket-platform-realm.json:/opt/keycloak/data/import/event-ticket-platform-realm.json:z
    command:
      - start-dev
      - --db=dev-file
      - --import-realm
    networks:
      - backend-network
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/event-ticket-platform/protocol/openid-connect/certs
    depends_on:
      - db
      - keycloak
    networks:
      - backend-network
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend
      - keycloak
    networks:
      - backend-network
    restart: always

networks:
  backend-network:
    driver: bridge
