export enum EventType {
  CONCERT = 'CONCERT',
  CONFERENCE = 'CONFERENCE',
  MEETUP = 'MEETUP',
  WORKSHOP = 'WORKSHOP',
  FESTIVAL = 'FESTIVAL',
  SPORTS = 'SPORTS',
  THEATER = 'THEATER',
  EXHIBITION = 'EXHIBITION',
  PARTY = 'PARTY',
  OTHER = 'OTHER'
}
